/** Flag emoji for each language code (representative country/region). */
const FLAGS: Record<string, string> = {
  english: '🇬🇧',
  arabic: '🇦🇪',
  bengali: '🇧🇩',
  bulgarian: '🇧🇬',
  catalan: '🇦🇩',
  'chinese-simplified': '🇨🇳',
  'chinese-hong-kong': '🇭🇰',
  'chinese-traditional': '🇹🇼',
  croatian: '🇭🇷',
  czech: '🇨🇿',
  danish: '🇩🇰',
  dutch: '🇳🇱',
  estonian: '🇪🇪',
  finnish: '🇫🇮',
  french: '🇫🇷',
  german: '🇩🇪',
  greek: '🇬🇷',
  hebrew: '🇮🇱',
  hindi: '🇮🇳',
  hungarian: '🇭🇺',
  icelandic: '🇮🇸',
  indonesian: '🇮🇩',
  italian: '🇮🇹',
  japanese: '🇯🇵',
  khmer: '🇰🇭',
  korean: '🇰🇷',
  lao: '🇱🇦',
  latvian: '🇱🇻',
  lithuanian: '🇱🇹',
  macedonian: '🇲🇰',
  malay: '🇲🇾',
  maltese: '🇲🇹',
  norwegian: '🇳🇴',
  polish: '🇵🇱',
  portuguese: '🇵🇹',
  'portuguese-brazil': '🇧🇷',
  romanian: '🇷🇴',
  russian: '🇷🇺',
  serbian: '🇷🇸',
  slovak: '🇸🇰',
  slovenian: '🇸🇮',
  spanish: '🇪🇸',
  swahili: '🇰🇪',
  swedish: '🇸🇪',
  tagalog: '🇵🇭',
  thai: '🇹🇭',
  turkish: '🇹🇷',
  ukrainian: '🇺🇦',
  vietnamese: '🇻🇳',
};

export function flagForLanguage(code: string): string {
  return FLAGS[code] ?? '🏳️';
}
